# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8bd7718949fe115b750ab262fd1382befc574614c547ac5c9f9d0fe5531ef37bbfbabc7f8d7d26dc389dfaf89468e711f27bc8b9bdc602a00d383b8e1bff43f

test:
  secret_key_base: ecd52d1c9ff588ae333cd4a95dbd6e5774b7f24677b4f307621de6806a4c16a62f5569f5d2f218ae97e1d4f4177fc3fe496d524aa9e6e852ae423bc4337d1835

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
